export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",

  CONSENT_VERSION_MISSING = "CONSENT_VERSION_MISSING",
  CONSENT_VERSION_NOT_FOUND = "CONSENT_VERSION_NOT_FOUND",
  CONSENT_KEY_MISMATCH = "CONSENT_KEY_MISMATCH",
  CONSENT_DUPLICATE = "CONSENT_DUPLICATE",

  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  REPORT_NOT_DELIVERED = "REPORT_NOT_DELIVERED",
  PDF_NOT_READY = "PDF_NOT_READY",

  INVALID_ORDER_STATE = "INVALID_ORDER_STATE",
  PACKAGE_INACTIVE = "PACKAGE_INACTIVE",

  REPORT_NOT_PUBLISHED = "REPORT_NOT_PUBLISHED",
  REPORT_EMPTY = "REPORT_EMPTY",

  PDF_NOT_READY_UI = "PDF_NOT_READY_UI",
  PDF_GENERATION_FAILED = "PDF_GENERATION_FAILED",
  MAX_RETRY_REACHED = "MAX_RETRY_REACHED",

  WEBHOOK_SIGNATURE_INVALID = "WEBHOOK_SIGNATURE_INVALID",
}
